/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gq_glowman554_libc_SmartPointer */

#ifndef _Included_gq_glowman554_libc_SmartPointer
#define _Included_gq_glowman554_libc_SmartPointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gq_glowman554_libc_SmartPointer
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_gq_glowman554_libc_SmartPointer_malloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     gq_glowman554_libc_SmartPointer
 * Method:    realloc
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_gq_glowman554_libc_SmartPointer_realloc
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     gq_glowman554_libc_SmartPointer
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_SmartPointer_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gq_glowman554_libc_SmartPointer
 * Method:    index
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_gq_glowman554_libc_SmartPointer_index
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
