/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gq_glowman554_libc_stdio_Stdio */

#ifndef _Included_gq_glowman554_libc_stdio_Stdio
#define _Included_gq_glowman554_libc_stdio_Stdio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gq_glowman554_libc_stdio_Stdio
 * Method:    puts
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_stdio_Stdio_puts
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gq_glowman554_libc_stdio_Stdio
 * Method:    putchar
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_stdio_Stdio_putchar
  (JNIEnv *, jclass, jbyte);

#ifdef __cplusplus
}
#endif
#endif
