/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gq_glowman554_libc_memory_Pointer */

#ifndef _Included_gq_glowman554_libc_memory_Pointer
#define _Included_gq_glowman554_libc_memory_Pointer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    read_8
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_gq_glowman554_libc_memory_Pointer_read_18
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    write_8
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_memory_Pointer_write_18
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    read_16
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_gq_glowman554_libc_memory_Pointer_read_116
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    write_16
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_memory_Pointer_write_116
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    read_32
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_gq_glowman554_libc_memory_Pointer_read_132
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    write_32
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_memory_Pointer_write_132
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    read_64
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_gq_glowman554_libc_memory_Pointer_read_164
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    write_64
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_memory_Pointer_write_164
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_gq_glowman554_libc_memory_Pointer_malloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    realloc
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_gq_glowman554_libc_memory_Pointer_realloc
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_memory_Pointer_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gq_glowman554_libc_memory_Pointer
 * Method:    index
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_gq_glowman554_libc_memory_Pointer_index
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
