/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gq_glowman554_libc_Sizes */

#ifndef _Included_gq_glowman554_libc_Sizes
#define _Included_gq_glowman554_libc_Sizes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gq_glowman554_libc_Sizes
 * Method:    checkSizes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_Sizes_checkSizes
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
