/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gq_glowman554_libc_stdio_File */

#ifndef _Included_gq_glowman554_libc_stdio_File
#define _Included_gq_glowman554_libc_stdio_File
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gq_glowman554_libc_stdio_File
 * Method:    fopen
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_gq_glowman554_libc_stdio_File_fopen
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     gq_glowman554_libc_stdio_File
 * Method:    fclose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_gq_glowman554_libc_stdio_File_fclose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gq_glowman554_libc_stdio_File
 * Method:    fwrite
 * Signature: (JIIJ)I
 */
JNIEXPORT jint JNICALL Java_gq_glowman554_libc_stdio_File_fwrite
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     gq_glowman554_libc_stdio_File
 * Method:    fread
 * Signature: (JIIJ)I
 */
JNIEXPORT jint JNICALL Java_gq_glowman554_libc_stdio_File_fread
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     gq_glowman554_libc_stdio_File
 * Method:    ftell
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_gq_glowman554_libc_stdio_File_ftell
  (JNIEnv *, jclass, jlong);

/*
 * Class:     gq_glowman554_libc_stdio_File
 * Method:    fseek
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_stdio_File_fseek
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
