/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gq_glowman554_libc_string_Memory */

#ifndef _Included_gq_glowman554_libc_string_Memory
#define _Included_gq_glowman554_libc_string_Memory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gq_glowman554_libc_string_Memory
 * Method:    memcpy
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_string_Memory_memcpy
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     gq_glowman554_libc_string_Memory
 * Method:    memset
 * Signature: (JBI)V
 */
JNIEXPORT void JNICALL Java_gq_glowman554_libc_string_Memory_memset
  (JNIEnv *, jclass, jlong, jbyte, jint);

/*
 * Class:     gq_glowman554_libc_string_Memory
 * Method:    memcmp
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_gq_glowman554_libc_string_Memory_memcmp
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
